// Generated by scripts/build-v5-prospective-artifact.mjs. Do not edit by hand.

export const V5_PROSPECTIVE_ARTIFACT = {
  "version": "V5.0-PROSPECTIVE-SHADOW-FROZEN",
  "status": "SHADOW_ONLY",
  "productionInfluence": 0,
  "featureOrder": [
    "passingEpa",
    "rushingEpa",
    "receivingEpa",
    "completionPct",
    "yardsPerAttempt",
    "sackRate",
    "interceptionRate"
  ],
  "coefficients": [
    -0.046537726713386664,
    0.0441609961463691,
    -0.03679695749341161,
    0.14562802586238305,
    0.022693786959322833,
    -0.1242323688590607,
    0.15347610298054107
  ],
  "standardization": {
    "means": [
      0.021694052634097474,
      0.12332085911415809,
      0.04363749832199838,
      -0.0007939061993651134,
      -0.012960224163819553,
      0.0001988532859547284,
      0.0000996670232464121
    ],
    "scales": [
      8.307411965299005,
      3.7347893729944617,
      7.0153431758982,
      0.06996159031994988,
      1.4428187414155007,
      0.03743363926085615,
      0.01720819482720178
    ]
  },
  "trainingSeasons": [
    2021,
    2022,
    2023,
    2024,
    2025
  ],
  "trainingGames": 1279,
  "ridge": 8,
  "residualScale": 0.5,
  "methodology": "Market-offset logistic residual using all-prior same-season regular-season efficiency, equal weighting, no pseudo-game shrinkage.",
  "sources": {
    "schedule": "https://github.com/nflverse/nflverse-data/releases/download/schedules/games.csv",
    "teamStats": "nflverse stats_team weekly releases"
  },
  "generatedAt": "2026-09-07T22:49:48.371Z",
  "artifactHash": "f873a580c43622f88f3e4407aef7b1908be42f82822a510986a13e7e8d627354"
} as const;
