// Generated by pnpm shadow:residual. V5 remains shadow-only.
export const V5_SHADOW_RESIDUAL = {
  "generatedAt": "2026-09-08T00:11:52.516Z",
  "status": "SHADOW_ONLY",
  "productionInfluence": 0,
  "model": "V5 offset-logistic market residual challenger",
  "caveat": "Historical market inputs are nflverse closing moneylines without observation timestamps. This is a conservative diagnostic against a later-information market proxy, not a same-time betting-edge claim.",
  "temporalPolicy": "Every game uses team-stat rows from the same season with week strictly less than the forecast game week. Model coefficients for a test game are fit only on games from earlier seasons or earlier weeks.",
  "source": {
    "schedule": "https://github.com/nflverse/nflverse-data/releases/download/schedules/games.csv",
    "teamStats": "nflverse stats_team weekly releases"
  },
  "features": [
    "passingEpaDiff",
    "rushingEpaDiff",
    "receivingEpaDiff",
    "completionPctDiff",
    "yardsPerAttemptDiff",
    "sackRateDiff",
    "interceptionRateDiff"
  ],
  "hyperparameters": {
    "minimumTrainingGames": 200,
    "ridge": 8,
    "learningRate": 0.04,
    "iterations": 500,
    "recency": 0.88,
    "correctionScales": [
      0,
      0.25,
      0.5,
      0.75,
      1
    ]
  },
  "coverage": {
    "eligibleGames": 1276,
    "outOfSampleGames": 1069
  },
  "market": {
    "games": 1069,
    "accuracy": 0.6725912067352666,
    "brier": 0.2094898133706173,
    "logLoss": 0.6059459031718856
  },
  "candidates": [
    {
      "scale": 0,
      "games": 1069,
      "accuracy": 0.6725912067352666,
      "brier": 0.2094898133706173,
      "logLoss": 0.6059459031718856,
      "deltaBrierVsMarket": 0,
      "deltaLogLossVsMarket": 0,
      "deltaAccuracyVsMarket": 0
    },
    {
      "scale": 0.25,
      "games": 1069,
      "accuracy": 0.6782039289055192,
      "brier": 0.20924195894116776,
      "logLoss": 0.6053055762948888,
      "deltaBrierVsMarket": -0.00024785442944955105,
      "deltaLogLossVsMarket": -0.0006403268769967774,
      "deltaAccuracyVsMarket": 0.005612722170252549
    },
    {
      "scale": 0.5,
      "games": 1069,
      "accuracy": 0.6772684752104771,
      "brier": 0.20925488112264673,
      "logLoss": 0.6052699054969707,
      "deltaBrierVsMarket": -0.00023493224797058176,
      "deltaLogLossVsMarket": -0.0006759976749148855,
      "deltaAccuracyVsMarket": 0.004677268475210439
    },
    {
      "scale": 0.75,
      "games": 1069,
      "accuracy": 0.6782039289055192,
      "brier": 0.2095144394023189,
      "logLoss": 0.6058218862679622,
      "deltaBrierVsMarket": 0.000024626031701585616,
      "deltaLogLossVsMarket": -0.00012401690392338516,
      "deltaAccuracyVsMarket": 0.005612722170252549
    },
    {
      "scale": 1,
      "games": 1069,
      "accuracy": 0.6725912067352666,
      "brier": 0.21000512395009202,
      "logLoss": 0.6069432860425429,
      "deltaBrierVsMarket": 0.0005153105794747093,
      "deltaLogLossVsMarket": 0.0009973828706573151,
      "deltaAccuracyVsMarket": 0
    }
  ],
  "bestByBrier": {
    "scale": 0.25,
    "games": 1069,
    "accuracy": 0.6782039289055192,
    "brier": 0.20924195894116776,
    "logLoss": 0.6053055762948888,
    "deltaBrierVsMarket": -0.00024785442944955105,
    "deltaLogLossVsMarket": -0.0006403268769967774,
    "deltaAccuracyVsMarket": 0.005612722170252549
  },
  "fullResidual": {
    "games": 1069,
    "accuracy": 0.6725912067352666,
    "brier": 0.21000512395009202,
    "logLoss": 0.6069432860425429,
    "calibration": [
      {
        "label": "50-55%",
        "games": 150,
        "predicted": 0.5242404176578518,
        "actual": 0.5533333333333333
      },
      {
        "label": "55-60%",
        "games": 183,
        "predicted": 0.5750999967221301,
        "actual": 0.5683060109289617
      },
      {
        "label": "60-65%",
        "games": 192,
        "predicted": 0.6231841490999495,
        "actual": 0.6458333333333334
      },
      {
        "label": "65-70%",
        "games": 151,
        "predicted": 0.6759176301321955,
        "actual": 0.6556291390728477
      },
      {
        "label": "70-75%",
        "games": 135,
        "predicted": 0.7254569843431043,
        "actual": 0.7407407407407407
      },
      {
        "label": "75-80%",
        "games": 115,
        "predicted": 0.7747184576654355,
        "actual": 0.7565217391304347
      },
      {
        "label": "80-85%",
        "games": 75,
        "predicted": 0.823350521852453,
        "actual": 0.7733333333333333
      },
      {
        "label": "85-90%",
        "games": 49,
        "predicted": 0.8736523681199203,
        "actual": 0.9183673469387755
      },
      {
        "label": "90-100%",
        "games": 19,
        "predicted": 0.9161943252640165,
        "actual": 1
      }
    ]
  },
  "marketCalibration": [
    {
      "label": "50-55%",
      "games": 135,
      "predicted": 0.5254403993989097,
      "actual": 0.48148148148148145
    },
    {
      "label": "55-60%",
      "games": 228,
      "predicted": 0.5760959512702797,
      "actual": 0.6403508771929824
    },
    {
      "label": "60-65%",
      "games": 196,
      "predicted": 0.6237029888540417,
      "actual": 0.6275510204081632
    },
    {
      "label": "65-70%",
      "games": 146,
      "predicted": 0.6760442430055974,
      "actual": 0.6575342465753424
    },
    {
      "label": "70-75%",
      "games": 126,
      "predicted": 0.7244654802267457,
      "actual": 0.7698412698412699
    },
    {
      "label": "75-80%",
      "games": 122,
      "predicted": 0.7734154564189228,
      "actual": 0.7377049180327869
    },
    {
      "label": "80-85%",
      "games": 56,
      "predicted": 0.8228418201336496,
      "actual": 0.8035714285714286
    },
    {
      "label": "85-90%",
      "games": 53,
      "predicted": 0.8712658807747219,
      "actual": 0.9433962264150944
    },
    {
      "label": "90-100%",
      "games": 7,
      "predicted": 0.9112513823962708,
      "actual": 1
    }
  ],
  "bySeason": [
    {
      "season": 2021,
      "market": {
        "games": 48,
        "accuracy": 0.6458333333333334,
        "brier": 0.20070407799044118,
        "logLoss": 0.5868089309044381
      },
      "fullResidual": {
        "games": 48,
        "accuracy": 0.6666666666666666,
        "brier": 0.19724592309143432,
        "logLoss": 0.578570988986364
      }
    },
    {
      "season": 2022,
      "market": {
        "games": 254,
        "accuracy": 0.6535433070866141,
        "brier": 0.2085226688121687,
        "logLoss": 0.6033238902708183
      },
      "fullResidual": {
        "games": 254,
        "accuracy": 0.6535433070866141,
        "brier": 0.21165358454354796,
        "logLoss": 0.6106667325693541
      }
    },
    {
      "season": 2023,
      "market": {
        "games": 256,
        "accuracy": 0.6875,
        "brier": 0.2172817910838267,
        "logLoss": 0.6245213076275091
      },
      "fullResidual": {
        "games": 256,
        "accuracy": 0.68359375,
        "brier": 0.22013877269221893,
        "logLoss": 0.6318314334664037
      }
    },
    {
      "season": 2024,
      "market": {
        "games": 256,
        "accuracy": 0.7109375,
        "brier": 0.20011409697318253,
        "logLoss": 0.5869969967430135
      },
      "fullResidual": {
        "games": 256,
        "accuracy": 0.71875,
        "brier": 0.1968752935023692,
        "logLoss": 0.5796562541712041
      }
    },
    {
      "season": 2025,
      "market": {
        "games": 255,
        "accuracy": 0.6431372549019608,
        "brier": 0.21369690011279757,
        "logLoss": 0.612534853959569
      },
      "fullResidual": {
        "games": 255,
        "accuracy": 0.6352941176470588,
        "brier": 0.21377279127209375,
        "logLoss": 0.6109834007854497
      }
    }
  ],
  "verdict": "A nonzero correction is descriptively best in this shadow replay. It remains non-promotion-eligible until stability, bootstrap uncertainty, and prospective same-time validation are demonstrated."
} as const;
