// Generated by pnpm v7:artifact. V7 remains shadow-only.
export const V7_PROSPECTIVE_ARTIFACT = {
  "version": "V7.0-INTELLIGENCE-SHADOW-PROSPECTIVE",
  "status": "SHADOW_ONLY",
  "productionInfluence": 0,
  "featureOrder": [
    "passingEpaDiff",
    "rushingEpaDiff",
    "receivingEpaDiff",
    "completionPctDiff",
    "yardsPerAttemptDiff",
    "sackRateDiff",
    "interceptionRateDiff",
    "defensivePassingEpaDiff",
    "defensiveRushingEpaDiff"
  ],
  "football": {
    "intercept": 0.18267183506334236,
    "coefficients": [
      0.15058123547190924,
      0.2202369948223071,
      0.12550265173228917,
      0.16247755732710312,
      0.13287977555502428,
      -0.18733691162857052,
      0.12633053355693252,
      0.09803439876274996,
      0.1594499280972487
    ],
    "standardization": {
      "means": [
        0.019650494475690516,
        0.13334740145994187,
        0.05486112896346719,
        -0.0010539188056803408,
        -0.01869221846617422,
        0.00021303124847073303,
        0.00010847714133773509,
        -0.0119768275087862,
        -0.016039341800722296
      ],
      "scales": [
        8.493627202209224,
        3.8208761718569586,
        7.181043290815921,
        0.07111622632051946,
        1.4636873530928323,
        0.03833037369184478,
        0.01774015932092341,
        7.245571367945705,
        3.627149397990532
      ]
    }
  },
  "residual": {
    "intercept": -0.02139168173646665,
    "coefficients": [
      -0.018504997542998683,
      0.034128179697655636,
      -0.010306115721906478,
      0.11674001856688146,
      0.01625325984380316,
      -0.07837934111546015,
      0.13866974764975695,
      -0.15255866550370809,
      0.07228279946754843
    ],
    "standardization": {
      "means": [
        0.019650494475690516,
        0.13334740145994187,
        0.05486112896346719,
        -0.0010539188056803408,
        -0.01869221846617422,
        0.00021303124847073303,
        0.00010847714133773509,
        -0.0119768275087862,
        -0.016039341800722296
      ],
      "scales": [
        8.493627202209224,
        3.8208761718569586,
        7.181043290815921,
        0.07111622632051946,
        1.4636873530928323,
        0.03833037369184478,
        0.01774015932092341,
        7.245571367945705,
        3.627149397990532
      ]
    },
    "appliedScale": 0.25
  },
  "trainingSeasons": [
    2021,
    2022,
    2023,
    2024,
    2025
  ],
  "trainingGames": 1276,
  "temporalPolicy": "Current-season regular-season team statistics must be from weeks strictly before the forecast week. Week 1 has no eligible current-season team sample.",
  "unavailableInputs": [
    "timestamped historical player availability",
    "depth rank",
    "starter confirmation",
    "weather observation history",
    "market movement history"
  ],
  "artifactHash": "d953e68ef96553cfd2e7f2754eddcadae659671f034842c657e1c7a8bd6813de"
} as const;
